name: Helm Create Tag from Version Action

description: |-
  Automates the process of pushing merge commits into a "release" branch from
  either a source branch (ie `main`) or from Git Tags/Releases.

author: Matt Wise <matt@nextdoor.com>

branding:
  color: green
  icon: arrow-up-right

inputs:
  dry:
    description: Whether or not this action will run in a dry run or not.
    default: false
    required: false

  verbose:
    description: >-
      Should the script output all of the commands (set -x) while its running or not?
    default: false
    required: false

  chart_dir:
    description: >-
      The path to where the chart lives (specifically the directory
      that holds the Chart.yaml file).
    default: chart
    required: true

  create_release:
    description: Whether or not to also create a Github Release for this tag?
    default: true
    required: true

runs:
  using: docker
  image: Dockerfile
